### ISSUE TITLE
Blank page when trying to authenticate account for export

### ISSUE THREAD

**Issue by giantplaceholder** [snikket-im/xmpp-account-exporter#1]
Hi there,

I've tried to export some data using an account at jabber.ru XMPP server.
Before this attempt, I've logged into it using Converse.js and verified that it is actually still exists and that my credentials are correct.

After entering the credentials and pressing "Connect" button, page clears up, leaving only the title ("XMPP account exporter (beta)") visible, with no other contents. Browser console reports the following:

```
Converse loaded! 
Object
index.js:486 connected! false 
Object
 and 
Object
migrate.modernxmpp.org/:1 [DOM] Found 2 elements with non-unique id #jid-el: (More info: https://goo.gl/9p2vKq) 
 
log.js:72  2022-01-07T08:00:10.048Z INFO: Disconnect was called 
log.js:66  2022-01-07T08:00:10.049Z WARNING: Disconnect was called before Strophe connected to the server 
index.js:141 Uncaught ReferenceError: parseXPath is not defined
    at XMLHttpRequest.xhr.onload (index.js:141:18)
DevTools failed to load source map: Could not load content for https://migrate.modernxmpp.org/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://migrate.modernxmpp.org/bootstrap/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Browser: Google Chrome 97.0.4692.71

**Comment by mwild1** [comment]
Hi, thanks for the report! This is hopefully now fixed in the latest deployment. Let me know if you have any further issues!
