### ISSUE TITLE
Export/import bookmarks

### ISSUE THREAD

**Issue by raucao** [snikket-im/xmpp-account-exporter#5]
It seems that currently neither private storage bookmarks nor PEP-native ones get exported by the app.

**Comment by Zash** [comment]
Correct, there's an open PR for that: https://github.com/snikket-im/xmpp-account-exporter/pull/2

**Comment by cal0pteryx** [comment]
XEP-0048 (v1.0) is now available.

**Comment by licaon-kter** [comment]
So close this as fixed?

**Comment by Zash** [comment]
Yes, tho I don't have that access, guessing only @mwild1 does, so pingeth'
