### ISSUE TITLE
Transfer contact names as well when using "Upload to another account" option 

### ISSUE THREAD

**Issue by speedygonzales9** [snikket-im/xmpp-account-exporter#9]
Hi, 

I am trying to transfer my account data from `@movim.eu` to my new Snikket account. However when using the `Upload to another account...` option, it transfers **only** their Jabber ID's and **not** their contact names along with it. However if I `download account data` in a XML file, it includes all of the contact names. I would like the `Upload to another account` option to transfer their Jabber ID's along with their appropriate contact names. Can I make this a feature request please? 

Thank you

**Comment by Zash** [comment]
If someone wants to take a look then around here is where it uploads contacts:

https://github.com/snikket-im/xmpp-account-exporter/blob/8ec121b4ff33485432f5c8bbbb39023877ff9a40/index.js#L42-L87

The code should be tweaked to include the [name attribute](https://xmpp.org/rfcs/rfc6121.html#roster-syntax-items-name), both when updating existing contacts and when adding new ones.
